# Generated by Django 4.2 on 2024-04-28 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_notes_options_homework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='is_finishrd',
            new_name='is_finished',
        ),
    ]
